!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2.2.1)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_time_get_time_in_scs (get_time_in_scsf2pywrap)
      use time, only : get_time_in_scs
      real(kind=8) get_time_in_scsf2pywrap
      get_time_in_scsf2pywrap = get_time_in_scs()
      end subroutine f2pywrap_time_get_time_in_scs
      
      subroutine f2pyinittime(f2pysetupfunc)
      interface 
      subroutine f2pywrap_time_get_time_in_scs (get_time_in_scsf2pywrap,&
     & get_time_in_scs)
      real(kind=8) get_time_in_scsf2pywrap
      end subroutine f2pywrap_time_get_time_in_scs
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_time_get_time_in_scs)
      end subroutine f2pyinittime


